include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true

    # ✅ Code clarity
    always_declare_return_types: true
    always_use_package_imports: true

    # ✅ Error prevention
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_unnecessary_containers: true
    unnecessary_null_checks: true
    no_leading_underscores_for_local_identifiers: true

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.gen.dart
    - lib/generated/**